# Generated by Django 4.2.1 on 2023-06-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='kategori',
        ),
    ]
