# Generated by Django 4.2.1 on 2023-06-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_alter_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
