# Generated by Django 4.2.1 on 2023-06-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_remove_item_slug_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
